### ISSUE TITLE
Mod Menu for input serialization

### ISSUE THREAD

**Issue by ghost** [gallexme/LuaPlugin-GTAV#1]
I've written Mod Menu, https://www.gta5-mods.com/scripts/mod-menu-no-more-hotkeys, to try to sidestep the issue of mods catching keyboard input in parallel, creating key conflicts and requiring configuration files to adjust keybinds. Mod Menu also implements input through the game's natives, and includes a header modMenu.h that wraps and documents some natives I've found useful for the in game inputs. Please use that information however you see fit.

I would love to support scripts loaded by LuaPlugin within Mod Menu and have extended my (rudimentary) implementation for such.

Currently, MM requires the target dll to have implemented two exports

extern "C"{_declspec(dllexport) void __stdcall loadUI(LPCSTR empty){
// Call your menu or toggle active / inactive for example
}}

extern "C"{_declspec(dllexport) LPCSTR __stdcall getModName(LPCSTR empty){
return "Mod Name";
}}

For your purposes the "empty" parameters would contain the filename of the targeted script with .lua extension.

I'd love to see the mods work together.

**Comment by gallexme** [comment]
How should I return multiple mods?
Am 16.05.2015 03:31 schrieb "Neutrinobeam" notifications@github.com:

**Comment by ghost** [comment]
You shouldn't need to. The parameter would be the filename for that particular lua script found in /scripts/addins/.

If it were
dir /scripts/addins/
script1.lua
script2.lua
script3.lua

Then ModMenu would call (not necessarily in order)
visibleName1 = getModName(script1.lua);
visibleName2 = getModName(script2.lua);
visibleName3 = getModName(script3.lua);
and on user choice of visibleName2 would call
loadUI(script2.lua);.

Currently, there's no guarantee that a script wasn't deleted between scanning and executing though.
