### ISSUE TITLE
dose not download

### ISSUE THREAD

**Issue by spud128** [gallexme/LuaPlugin-GTAV#11]
when ever i click on the download link it comes up as a blank page and i  can't get many gta 5 mods with out it

**Comment by gallexme** [comment]
how to download:
Step 1 go to the Code tab
Step 2 press download as zip....
https://github.com/gallexme/LuaPlugin-GTAV/archive/master.zip

**Comment by kepi** [comment]
I think he is refering to download link on http://gtaforums.com/topic/789139-vrelhook-lua-plugin-for-script-hook-v/ which is leading to non-working web on http://178.62.61.147/index.php?title=Download

Would be great idea to update it.
