### ISSUE TITLE
GET_DISPLAY_NAME_FROM_VEHICLE_MODEL get a number but not a string

### ISSUE THREAD

**Issue by myshzzx** [gallexme/LuaPlugin-GTAV#2]
Lua V10:
local playerVehicle = PED.GET_VEHICLE_PED_IS_IN(PLAYER.PLAYER_PED_ID(), false)
local vehName = VEHICLE.GET_DISPLAY_NAME_FROM_VEHICLE_MODEL(ENTITY.GET_ENTITY_MODEL(playerVehicle))

which works well in V9

**Comment by gallexme** [comment]
Thanks for the issue

Can u check nativedb if the return type is correctly set to char*
Am 19.05.2015 06:55 schrieb "myshzzx" notifications@github.com:

**Comment by myshzzx** [comment]
static Any GET_DISPLAY_NAME_FROM_VEHICLE_MODEL(Any p0) { return invoke<Any>(0xB215AAC32D25D019, p0); } // B215AAC32D25D019 EC86DF39

natives.h in ScriptHookV_SDK.zip, last modified: 2015-5-2
ScriptHookV doesn't update since 2015-5-2
you mean all functions return string with type "Any" will not work?
I thought LUA.asi is compiled with natives.h, isn't it?

**Comment by gallexme** [comment]
no its compiled with : http://www.dev-c.com/nativedb/
to fix the bug go there http://www.dev-c.com/nativedb/func/info/b215aac32d25d019
change any to char*

**Comment by myshzzx** [comment]
If I can do that , I don't need to come here

**Comment by gallexme** [comment]
yep ^^
you just have to download  it here
