### ISSUE TITLE
GRAPHICS.GET_IS_WIDESCREEN() [SOLVED!]

### ISSUE THREAD

**Issue by 80T** [gallexme/LuaPlugin-GTAV#5]
It seems like since LUA v10 update and onwards, "GRAPHICS.GET_IS_WIDESCREEN()" native won't return the expected value any more.
I've tried downgrading back to LUA v9 and the native it's correctly returning "true"/"false" as it should.
Back to LUA v10/v10.1 and the native always returns "true" no matter what.

Note: I've only tried the SDK versions, so I can't tell for now if the problem persists with the standard revisions as well.

**Comment by gallexme** [comment]
nativedb says its ANY which is always returned as number
change it there to bool

**Comment by 80T** [comment]
Sorry... my bad. I've got confused because for whatever reason LUA v9 was apparently returning a bool... ? It's working now, returning "any" 0/1.

Do you mean I should edit the DB page and change "any" to "Bool"... ?

**Comment by gallexme** [comment]
yep and then wait 10-20 min and take the new .asi

**Comment by 80T** [comment]
Ok, thx. I did that, but reverted back way too quickly. I was afraid to let the changes there. I wasn't sure I should screw around with that DB. I guess I'll give it another try again later :)

EDIT: Ok, I've waited longer this time and it worked :dart: Thx!
