### ISSUE TITLE
gta v c++

### ISSUE THREAD

**Issue by drmarc8** [gallexme/LuaPlugin-GTAV#6]
i am trying to install lua mods to do this you need to install c++ but the link that is provided in this link
(http://gtaforums.com/topic/789139-vrelhook-lua-plugin-for-script-hook-v/) when i try to download c++ it does not download it says retry if not downloaded in 30 seconds but i try even after 2 hours it does not work.
since the new update script hook was malfunctioning but they released a new update will this case be for the lua? is c++ needed for lua mods? please answer this it would mean alot.

thanks

**Comment by 80T** [comment]
1. You will need to download Visual C++ with Internet Explorer (from M$ official pages).
2. LUA only needs updating for new natives or for performance/features if needed be. 
3. Yes, Visual C++ it's needed for the LUA.asi to work.

**Comment by drmarc8** [comment]
@80T can you please provide a link for the visual C++ 
also can you send me a link when lua is updated?

thanks for your help :P

**Comment by 80T** [comment]
Visual C++
http://www.mediafire.com/download/vv4ti4g5zrwrimz/Visual_C++_Redistributable_Packages_for_Visual_Studio_2013.zip

LUA Plugin:
http://178.62.61.147/index.php?title=Download

**Comment by drmarc8** [comment]
thanks alot! @80T

**Comment by drmarc8** [comment]
@80T i installed both x86 and x64 and installed lua like it shows in this video (https://www.youtube.com/watch?v=FxBgkd4tLm0) is this correct? if not can you please send me a correct video on how to installed lua mods?

**Comment by drmarc8** [comment]
@80T  correction he did not show us to install c++ in the video but he only showed us how to install lua mods

**Comment by 80T** [comment]
Yes, in the video he forgot to cover the VC++ redist. installation. Just follow the video instructions and install both VC++ packages and you should be all set to use LUA scripts.

**Comment by drmarc8** [comment]
okay just done it and the lua mods still don't work
idk if this is just my computer or if this is incorrect do you use lua? 
how did you install it if you are a user?
.

**Comment by 80T** [comment]
Yes, I use LUA scripts and they're working fine. If you have the latest version of Script Hook V, LUA plugin and VC++ installed there's no reason for the LUA scripts not to work...

**Comment by drmarc8** [comment]
i have no idea what is wrong i guess i cant use lua scripts also thanks for your help :) means a lot even if it did not work out. @80T

**Comment by drmarc8** [comment]
NEVER MIND IT WORKED THANKS SO MUCH!!!!  DID NOT USE THE MOD RIGHT!! thanks yesss!! @80T

**Comment by 80T** [comment]
It's good that all turned out well and working. HF!

**Comment by drmarc8** [comment]
yeah hf! but... i cant install .cs files i do what it says in this video but idk? it does not work even some ppl in the comments said that the .cs files dont work can you please help again ..... sorry! :(

@80T

**Comment by 80T** [comment]
For .cs scripts you will need Script Hook V .Net .asi plugin... Just as you needed LUA.asi for LUA scripts... http://gtaforums.com/topic/789907-vrel-community-script-hook-v-net/ and of course, Net Framework 4.5 https://www.microsoft.com/download/details.aspx?id=30653 (which you will download with Internet Exploer not Firefox or Chrome, etc... )

**Comment by drmarc8** [comment]
okay thanks @80T
