### ISSUE TITLE
Development State

### ISSUE THREAD

**Issue by Alan-FGR** [gallexme/LuaPlugin-GTAV#7]
Hey there, it seems this project is not getting much love, specially because the last autobuild was 20 days ago... perhaps you guys could take one of the autobuilds (perhaps the latest one?) or perhaps build a new  version with the updated natives and call it 'stable' (perhaps v11) and upload it somewhere (like gta5-mods so there's the donate button) so I could update my mods for that version and also their dev status.

Or perhaps if you're not interested in developing this further maybe you could authorize me to mirror a version (here on github) so I could point my mods to it... or maybe you could opensource it :P.

There's no way I'm gonna port my persistance mod to c++, so this would really help. At the moment there's no version besides the autobuild that will work with all my mods.

What do you say :)?

**Comment by 80T** [comment]
I was also hoping for the new natives :D

**Comment by gallexme** [comment]
its still in development but it is going rather slowly as im not having time currently
things which work already but cant release to public are

ScriptThreads (u can run your .lua scripts in different scriptthreads)
Lua Lanes(Support for real threading)
and some more which i just cant think off atm

**Comment by 80T** [comment]
That's ok. It's good that you're still working on it and it's not dead :D

**Comment by Alan-FGR** [comment]
Yeah, I'm glad to hear this project is still alive. However, my problem still persists... my mods they aren't working with any of the 'released' versions of the Lua plugin (v9/v10/v10.1), and I'd like to point the users to some version that works. There are two quick solutions I can think of: you could release a new version of the plugin (perhaps the last autobuild as 10.2 or something) or perhaps in the mean time you could give me permission to maintain a 'mirror' of the version I'm using (I'd put it here on github).

I'd really like people to use my updated mods but atm it's a little bit hard because there's no lua plugin version I can point them to. If you release a new version (the hypothetical 10.2), I'd port all my mods to it, so you could host it, say, on gta5-mods.com. I don't know if I'm being clear, but I'm just asking you to upload the latest binary to gta5-mods.com (or other place). I just need a recent version I can link people to.

Thanks.

**Comment by Alan-FGR** [comment]
Hey there, it seems this project isn't receiving a lot of attention. @gallexme: perhaps you could upload the latest autobuild to gta5-mods or somehow make it a new official release so i could update my mods and link it.

If you have the time, it would be awesome if you could manually build a new version with the latest natives, but if not that's no big deal. I just need a link to a version newer than 10.1.

Thank you in advance.

**Comment by gallexme** [comment]
_Dead_

**Comment by Alan-FGR** [comment]
Yeah, I see. Thank you for developing the plugin, I had some good time
developing and playing with all my mods. I gave up selling AAA games though
:P. Perhaps I should've setup a donation button... have you received any
decent donations?

**Comment by gallexme** [comment]
@Alan-FGR u mean like 15$ which I got and he really wanted back? so i had to pay 20$ to paypal to cover their losses?
apart from that about 10$ enough for 2 months for the old website

**Comment by Alan-FGR** [comment]
That would be laughable if it wasn't sad :(. That's why I didn't even setup a donation button.

Don't get me wrong, the community (players) is mostly great, besides some random dicks who can't make a directory writable and think you must provide AAA support 24/7 like if they were paying you. But even though I had a good experience, it's quite stupid for someone like me to waste my time modding games like GTA V, some obvious reasons are that Rockstar don't want we to mod their games. You're treated like a criminal for modding their games, even though, still today I receive messages from people who bought the game on PC solely because of my mods, so we improve their sales and we're criminals. How grateful!

Also, as a poor indie gamedev I should be working to sell my own games and not collecting the hanging fruits of some overrated AAA game from a dickheads AAA studio. The big studios these days are all about bad marketing practices and money milking.

**Comment by gallexme** [comment]
@Alan-FGR you can laugh had a rant on paypal until they said they will pay 5$ back so i exactly earned and lost nothing :)
and great words :+1:

**Comment by Alan-FGR** [comment]
:smile_cat:
It's pretty hard to make any money with games these days. Donation models are surely not helping much too. Anyway, I wish you success and a great new year! :smile:
