### ISSUE TITLE
cant download it

### ISSUE THREAD

**Issue by dman21211212** [gallexme/LuaPlugin-GTAV#8]
when i click the download link it loads for like 30 seconds and then says this webpage is not available.

**Comment by Alan-FGR** [comment]
are you talking about this link:
https://github.com/gallexme/LuaPlugin-GTAV/archive/master.zip
?

**Comment by kepi** [comment]
I think he is refering to download link on http://gtaforums.com/topic/789139-vrelhook-lua-plugin-for-script-hook-v/ which is leading to non-working web on http://178.62.61.147/index.php?title=Download

Would be great idea to update it.

**Comment by Alan-FGR** [comment]
Yeah, that's the old @gallexme website. Certainly could use an update to the binary hosted on GitHub.
